# Generated by Django 5.0.5 on 2024-06-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quest_id", models.CharField(max_length=10, unique=True)),
                ("quest_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_range", models.CharField(max_length=20)),
                ("age_group", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=50)),
                ("weight", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_text", models.TextField()),
                ("sentiment_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quest.quest"
                    ),
                ),
            ],
        ),
    ]
